"""init

Revision ID: 6d31c5bcc898
Revises: 
Create Date: 2022-04-07 18:21:34.326598

"""
import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d31c5bcc898"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hairproduct",
        sa.Column("product_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("product_category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("product_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("straight", sa.Boolean(), nullable=True),
        sa.Column("wavy", sa.Boolean(), nullable=True),
        sa.Column("curly", sa.Boolean(), nullable=True),
        sa.Column("coily", sa.Boolean(), nullable=True),
        sa.Column("fine", sa.Boolean(), nullable=True),
        sa.Column("medium", sa.Boolean(), nullable=True),
        sa.Column("thick", sa.Boolean(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("product_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("hairproduct")
    # ### end Alembic commands ###
